AWSTemplateFormatVersion: '2010-09-09'
Description: Restore Banco de Dados Postgres - RDS

##############################
#        Parameters          #
##############################
Parameters:
  RDSName:
    Description: Nome do DB
    Type: String
    Default: letscode-backup
  RDSInstanceType:
    Type: String
    Description: Tipo instancia RDS
    Default: db.t2.micro
  Engine:
    Description: Tipo Sistema de Gerenciamento de Banco de Dados
    Type: 'String'
    Default: postgres
  EngineVersion:
    Description: Versão do Sistema de Gerenciamento de Banco de Dados
    Type: 'String'
    Default: "12.7"
  DBAllocatedStorage:
    Default: '20'
    Description: Disco do banco de dados
    Type: Number
  StorageType:
    Description: Tipo de armazenamento, valores válidos standard | gp2 | io1
    Type: 'String'
    Default: gp2
  MultiAZ:
    Description: Multi-AZ
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  MonitoringInterval:
    Description: Especificar o valor entre 0, 1, 5, 10, 15, 30, 60
    Type: Number
    Default: '0'
  BkpRetentionPeriod:
    Description: Periodo dos backups a serem retidos, deve ser um valor de 0 a 35. 0 desativa backups automatizados
    Type: Number
    Default: '7'
  BkpWindows:
    Description: O intervalo de tempo diário durante o qual os backups automatizados serão criados. Deve estar no formato Deve estar no formato hh24:mi-hh24:mi
    Type: String
    Default: "06:15-07:15"
  DBSnapshotIdentifier:
    Description: Criar instancia RDS a partir de um snapshot 
    Type: String
    Default: "arn:aws:rds:us-east-2:536371812725:snapshot:letscode-backup"

##############################
#        Resources          #
##############################
Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
      DBInstanceIdentifier: !Ref RDSName
      AllocatedStorage: !Ref 'DBAllocatedStorage'
      StorageType: !Ref StorageType
      DBInstanceClass: !Ref RDSInstanceType
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      MultiAZ: !Ref 'MultiAZ'
      PubliclyAccessible: true
      StorageEncrypted: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: !Ref 'BkpRetentionPeriod'
      PreferredBackupWindow: !Ref 'BkpWindows'
      MonitoringInterval: !Ref 'MonitoringInterval'